# Generated by Django 5.2 on 2025-04-22 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='1st exercise of the day, 2nd exercise.... (1 = DB Press, 2 = Pec Fly')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Day number in the split (e.g. 1 = Push, 2 = Pull)')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='overload_tracker.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('rir', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order', models.PositiveIntegerField(help_text='1st Set, 2nd Set(1 = 1st Set)')),
                ('exercise_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='overload_tracker.exerciselog')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='overload_tracker.workoutday'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='overload_tracker.workoutday')),
            ],
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='overload_tracker.workoutsession'),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='overload_tracker.workoutsplit'),
        ),
    ]
