# Generated by Django 5.2 on 2025-04-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overload_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsplit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
