# Generated by Django 5.2 on 2025-04-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overload_tracker', '0002_workoutsplit_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsplit',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
